server:
  port: 8889
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yinde/test
          searchPaths: '{application}'
          #username: 
          #password: 
      #label: master
  application:
    name: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/