#server:
#  port: 8083
#spring:
#  application:
#    name: zuul
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8762/eureka/
#zuul:
#  #ignored-headers: uu
#  routes:
#    #first: /first/**
#      #path: /first/**
#      #url: http://localhost:8080
#    client : /client/**
#    client1 : /client1/**
    
spring:
 # application:
  #  name: client
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      label: master
      profile: dev
      #uri: http://localhost:8888
      name: client,common,zuul