#server:
#  port: 8080
spring:
  cloud:
     bus:
      trace:
        enabled: true
     config:
      discovery:
        enabled: true
        service-id: config-server
      label: master
      profile: dev
      name: client,common
      
      
#management:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh,bus-env
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8762/eureka/
#feign:
#  hystrix:
#   enabled: true

