spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      label: master
      profile: dev
      name: client,common,client-1
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8762/eureka/
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
#feign:
#  hystrix:
#   enabled: true 

